<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\deims_routines\Controller\Perun;

/**
 * Causes the listed function to run once a week
 */
function deims_routines_cron() {
  $state = \Drupal::state();

  $last_run = $state->get('deims_routines.last_run', 0);
  $now = \Drupal::time()->getRequestTime();

  // 7 days = 604800 seconds
  if ($now - $last_run >= 604800) {

    // Your weekly logic here
    \Drupal::logger('deims_routines')->info('Running weekly task.');

    // Update last run timestamp
    $state->set('deims_routines.last_run', $now);
	
	// trigger whatever function is needed
	// e.g. TERN updates
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function deims_routines_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Get the current user
  $current_user = \Drupal::currentUser();

  // Only allow admins to edit the email field
  if (!$current_user->hasPermission('administer users')) {
    // Make the email field read-only
    $form['account']['mail']['#disabled'] = TRUE;

    // Description to explain why it’s disabled
    $form['account']['mail']['#description'] = t('You cannot change your email address. For assistance please use the contact form.');
  }
}

# this module uses the entity_presave() hook to run whenever a location, site, activity or sensor is created or updated:
# https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_presave/10

/**
 * Implements hook_entity_presave()
 */
 
function deims_routines_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

	// only called when nodes are saved
	if ($entity->getEntityTypeId() == 'node') {

		$allowed_content_types = array("dataset", "activity", "observation_location", "sensor");
		$current_content_type = $entity->bundle();
		
		// save UUIDs from Drupal internal fields to materialised field
		if (in_array($current_content_type, $allowed_content_types)) {
			if ($entity->get('field_uuid')->isEmpty()) {
				$entity->field_uuid->value = $entity->uuid();
			}
		}

		// routines for sites
		if ($current_content_type == "site") {
			
			// save UUID tp DEIMS.ID field 
			if ($entity->get('field_deims_id')->isEmpty()) {
				$entity->field_deims_id->value = $entity->uuid();
			}
			
			// if a site is closed, remove all content from the affiliations field
			if (!$entity->get('field_status')->isEmpty()) {
				if ($entity->get('field_status')->target_id == 54180) {
					$entity->set('field_affiliation', []);
				}
			}
			
			// if the site name changes update the list of site names on PERUN
			$current_site_name = $entity->get('field_name')->value;
			$original_node = $entity->original ?? NULL;
			$old_site_name = $original_node->get('field_name')->value;

			if ($old_site_name !== $current_site_name) {
				// Instantiate Perun with HTTP client
				$perun = new Perun(\Drupal::service('http_client'));
				$perun->pushSiteNameList();
			}
			
			// Automatically remove unverified GERI (12967), LTER Europe (12974), ILTER (12833), TERN (245), NEON (12966) affiliation
			// and print status message
			$field_affiliation = $entity->get('field_affiliation');
			$paragraphs_to_delete = [];
			$indexes_to_remove = [];

			foreach ($field_affiliation as $index => $item) {
				
				if ($item->entity instanceof Paragraph) {
					
					$paragraph = $item->entity;
					
					if (!$paragraph->get('field_network')->isEmpty() && !$paragraph->get('field_network_verified')->isEmpty()) {
						
						$verified = $paragraph->get('field_network_verified')->value;
						if (!$verified) {
						
							$special_network_ids = array(12974, 12833, 12967, 245, 12966);
							$network_nid = $paragraph->get('field_network')->target_id;
							
							if (in_array($network_nid, $special_network_ids)) {
								// Mark for removal and deletion.
								$indexes_to_remove[] = $index;
								$paragraphs_to_delete[] = $paragraph;
								
								switch ($network_nid) {
									case 12967: // GERI
										\Drupal::messenger()->addMessage('Affiliation with GERI is granted centrally.', 'warning');
										break;
									case 12974: // eLTER
										\Drupal::messenger()->addMessage('Affiliation with eLTER is granted centrally following national-level accreditation.', 'warning');
										break;
									case 12833: // ILTER
										\Drupal::messenger()->addMessage('Affiliation with ILTER is granted centrally and reviewed biannually, contingent on national accreditation and full site profile completion.', 'warning');
										break;
									case 245: // TERN
										\Drupal::messenger()->addMessage('Affiliation with TERN can only be granted centrally by the TERN network management. Please directly get in touch with them regarding your site record on DEIMS.', 'warning');
										break;
									case 12966: // NEON
										\Drupal::messenger()->addMessage('Affiliation with NEON can only be granted centrally by the NEON network management. Please directly get in touch with them regarding your site record on DEIMS.', 'warning');
										break;
								}
							}
						}
					}
				}
			}
			
			// Remove references and delete paragraphs.
			foreach (array_reverse($indexes_to_remove) as $i) {
				$field_affiliation->removeItem($i);
			}

			foreach ($paragraphs_to_delete as $p) {
				$p->delete();
			}
			
		}
	}
}
